import type { ListingInput } from './repository';
import type { SourceAdapter } from './worker';

export const fixtureListings: ListingInput[] = [
  {
    canonicalKey: 'fixture:land-cruiser-atlanta-primary',
    sourceType: 'fixture',
    sourceItemId: 'land-cruiser-atlanta-primary',
    sourceUrl: null,
    title: '2011 Toyota Land Cruiser · clean Georgia title',
    year: 2011,
    make: 'Toyota',
    model: 'Land Cruiser',
    trim: null,
    priceAmount: 33_900,
    mileage: 139_200,
    titleStatus: 'clean',
    locationText: 'Alpharetta, GA',
    distanceMiles: 27,
    duplicateIdentity: { type: 'vehicle-fingerprint', value: 'synthetic-land-cruiser-alpha' },
  },
  {
    canonicalKey: 'fixture:land-cruiser-atlanta-secondary',
    sourceType: 'fixture-secondary',
    sourceItemId: 'land-cruiser-atlanta-secondary',
    sourceUrl: null,
    title: '2011 Toyota Land Cruiser · second fixture source',
    year: 2011,
    make: 'Toyota',
    model: 'Land Cruiser',
    trim: null,
    priceAmount: 33_900,
    mileage: 139_200,
    titleStatus: 'clean',
    locationText: 'Alpharetta, GA',
    distanceMiles: 27,
    duplicateIdentity: { type: 'vehicle-fingerprint', value: 'synthetic-land-cruiser-alpha' },
  },
  {
    canonicalKey: 'fixture:tahoe-z71-atlanta',
    sourceType: 'fixture',
    sourceItemId: 'tahoe-z71-atlanta',
    sourceUrl: null,
    title: '2004 Chevrolet Tahoe Z71 · clean title',
    year: 2004,
    make: 'Chevrolet',
    model: 'Tahoe',
    trim: 'Z71',
    priceAmount: 18_200,
    mileage: 88_600,
    titleStatus: 'clean',
    locationText: 'Marietta, GA',
    distanceMiles: 18,
  },
  {
    canonicalKey: 'fixture:supra-nationwide',
    sourceType: 'fixture',
    sourceItemId: 'supra-nationwide',
    sourceUrl: null,
    title: '1985 Toyota Supra · nationwide fixture',
    year: 1985,
    make: 'Toyota',
    model: 'Supra',
    trim: null,
    priceAmount: 24_500,
    mileage: 101_000,
    titleStatus: 'clean',
    locationText: 'Phoenix, AZ',
    distanceMiles: 1_850,
  },
  {
    canonicalKey: 'fixture:land-cruiser-salvage-reject',
    sourceType: 'fixture',
    sourceItemId: 'land-cruiser-salvage-reject',
    sourceUrl: null,
    title: '2012 Toyota Land Cruiser · salvage title fixture',
    year: 2012,
    make: 'Toyota',
    model: 'Land Cruiser',
    trim: null,
    priceAmount: 29_000,
    mileage: 142_000,
    titleStatus: 'salvage',
    locationText: 'Dallas, TX',
    distanceMiles: 790,
  },
  {
    canonicalKey: 'fixture:tahoe-missing-z71-reject',
    sourceType: 'fixture',
    sourceItemId: 'tahoe-missing-z71-reject',
    sourceUrl: null,
    title: '2003 Chevrolet Tahoe LS · trim conflict fixture',
    year: 2003,
    make: 'Chevrolet',
    model: 'Tahoe',
    trim: 'LS',
    priceAmount: 12_900,
    mileage: 91_000,
    titleStatus: 'clean',
    locationText: 'Nashville, TN',
    distanceMiles: 250,
  },
  {
    canonicalKey: 'fixture:supra-unknown-year-reject',
    sourceType: 'fixture',
    sourceItemId: 'supra-unknown-year-reject',
    sourceUrl: null,
    title: 'Toyota Supra · year needs review',
    year: null,
    make: 'Toyota',
    model: 'Supra',
    trim: null,
    priceAmount: 19_500,
    mileage: 120_000,
    titleStatus: 'clean',
    locationText: 'Portland, OR',
    distanceMiles: 2_600,
  },
];

export const fixtureSourceAdapter: SourceAdapter = {
  sourceType: 'fixture',
  poll: async () => fixtureListings.map((listing) => ({ ...listing })),
};
